trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Environment
    type: string
    default: dev

variables:
  - group: hola

jobs:
  - job: Testeo
    displayName: Testeo name
    steps:
      - script: echo $(test)
